### ISSUE TITLE
Use leveldb v1.22 for neo-cli release.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-node#472] opened 2019-09-30 03:00 UTC
I found leveldb has a critical BUG before which will cause mass leveldb files undisposed when frequently new a snapshot in a class file. Especially reproduce in Nep5Tracker plugin so I have to readjust the code to prevent it from this BUG. The bug could be seen here. https://github.com/google/leveldb/issues/320
It's fixed several months ago in v1.22 release. https://github.com/google/leveldb/pull/339
So I think we should include it in next neo-cli release until RocksDB applied.

**Comment by shargon** [comment] 2019-09-30 07:21
Jeff warned about this long ago, I agree, this should be included in the next release.

**Comment by superboyiii** [comment] 2019-09-30 07:25
> Jeff warned about this long ago, I agree, this should be included in the next release.

Yes, I also saw Jeff's comments. It's necessary for us to take place the old one.

**Comment by Ashuaidehao** [comment] 2019-11-13 09:47
https://www.nuget.org/packages/Neo.LevelDb.Dev/3.0.0-pre2
I have create a leveldb package with latest source code, can you help to test it?

**Comment by lock9** [comment] 2019-11-25 06:17
Hello @Ashuaidehao, how can we ensure this is working? Can we force the bug to happen somehow?

**Comment by Ashuaidehao** [comment] 2019-11-26 02:10
> Hello @Ashuaidehao, how can we ensure this is working? Can we force the bug to happen somehow?

@superboyiii have helped to test it, please notify us if this bug reproduct.
@lock9 , we also put the new leveldb at [here](https://github.com/neo-ngd/leveldb/releases), anyone can download and test it.

**Comment by superboyiii** [comment] 2019-11-29 06:32
@nicolegys is going to test if it's compatible with the old one on VM state, let's wait for the result.

**Comment by superboyiii** [comment] 2019-11-29 09:59
> Hello @Ashuaidehao, how can we ensure this is working? Can we force the bug to happen somehow?

Build

**Comment by shargon** [comment] 2019-11-29 12:32
@superboyiii Please, could you check if also this bug will disappear?

https://github.com/neo-project/neo/blob/15f59a7a4c8610b3d640a2840db6d76947bc3266/neo/IO/Data/LevelDB/DB.cs#L106-L109

**Comment by nicolegys** [comment] 2019-12-02 06:49
I ran 2.10.3 and my build on the same server, then compared their Storage folders.

Results:
<img width="960" alt="compareResult" src="https://user-images.githubusercontent.com/43694095/69936147-d75c5000-1511-11ea-9701-6ffa98a42629.png">

Only 3 files have differences:
<img width="958" alt="diff1" src="https://user-images.githubusercontent.com/43694095/69936160-e8a55c80-1511-11ea-8d79-2e5766b39447.png">
<img width="956" alt="diff2" src="https://user-images.githubusercontent.com/43694095/69936166-ec38e380-1511-11ea-96c0-a80f4cfc2a74.png">
<img width="954" alt="diff3" src="https://user-images.githubusercontent.com/43694095/69936173-f2c75b00-1511-11ea-9a24-4929ff8fd0e9.png">

The differences are caused by the plugin(StatesDumper) itself. It would miss some blocks occasionally.

So it's compatible with 2.10.3 on VM state.

**Comment by superboyiii** [comment] 2019-12-02 10:20
@shargon  @nicolegys will release  the content in ```try``` and remove ```catch``` to see if this leveldb could fix this issue.

**Comment by nicolegys** [comment] 2019-12-03 09:51
> @superboyiii Please, could you check if also this bug will disappear?
> 
> https://github.com/neo-project/neo/blob/15f59a7a4c8610b3d640a2840db6d76947bc3266/neo/IO/Data/LevelDB/DB.cs#L106-L109

@shargon I'm a little confused. 
I wanted to see what the bug is. So I released the content in try and remove catch, then using our old leveldb, syncing to the latest height. One day passed, this bug didn't appear. 
Maybe this old bug in .Net Core has been fixed...
Could you tell me how can I reproduce this bug, Or it appears very infrequently so i need to wait?

**Comment by shargon** [comment] 2019-12-03 11:46
I don't know hahaha i only read the comment, but it should come from long time ago...

**Comment by nicolegys** [comment] 2019-12-05 04:12
I test with this leveldb v1.22, installing the RpcNep5Tracker(master-2.x branch), and the bug still exists. #419 
![image](https://user-images.githubusercontent.com/43694095/70203007-7e312e00-1756-11ea-91c3-8994664caca6.png)
![image](https://user-images.githubusercontent.com/43694095/70203618-71153e80-1758-11ea-9f65-5752d9c5b5bc.png)

So at this time, I still need to use @superboyiii 's [fix](https://github.com/neo-project/neo-plugins/pull/139) , to make sure the number of chain files stable

**Comment by nicolegys** [comment] 2019-12-18 08:54
The issue that leveldb files undisposed has been fixed in the following PRs.
https://github.com/neo-project/neo-node/pull/507
https://github.com/neo-project/neo-modules/pull/167
https://github.com/neo-project/neo/pull/1350
https://github.com/neo-project/neo/pull/1366

And I have tested that v1.22 is compatible with the old one on VM state.

So should we include leveldb v1.22 in the next release?

**Comment by vncoelho** [comment] 2020-01-09 09:01
Let's go for it, @nicolegys @superboyiii @shargon @Ashuaidehao ?

@nicolegys and @superboyiii, you mentioned some problem with the Dump plugin? Does it proceed? If that is the case can you give an idea for us to fix it?

**Closed** 2020-11-13 09:49 UTC
