### ISSUE TITLE
node: Can't send all gas to an address in neo-cli

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-node#717] opened 2021-01-15 08:02 UTC
![image](https://user-images.githubusercontent.com/6295602/104697292-7cec7600-574a-11eb-9b15-062515a3f899.png)

**Description**
I want to transfer all my GAS to another address, and I can't do that in neo-cli.

**Expected**
Automatically deduct the fee and transfer the balance to this address.

**Suggestion:** 
Can it automatically deduct the fee from the transfer amount when sending all?

**Comment by ProDog** [comment] 2021-01-15 09:00
A nice feature 🆒.

**Comment by shargon** [comment] 2021-01-15 09:01
It can be done changing the type to `string` and parsing the string inside the method

**Comment by superboyiii** [comment] 2021-01-15 10:36
> It can be done changing the type to `string` and parsing the string inside the method

Since we're still calculating NetFee per byte not per KB, how can we calculate that accurately if the tx is just over 1KB after signature is added.

**Comment by shargon** [comment] 2021-01-15 11:12
> Since we're still calculating NetFee per byte not per KB, how can we calculate that accurately if the tx is just over 1KB after signature is added.

With zero padding for the big integer amount. The size will be the same for 1 and for 10000000. You will need to compute only twice the transaction, one for get the fee with `0000000000000001`, substract the fee from the amount and sign.

**Comment by shargon** [comment] 2021-01-15 11:15
But it would be nice to have this https://github.com/neo-project/neo/pull/2008 otherwise, you will earn gas :)

**Comment by superboyiii** [comment] 2021-01-15 11:25
> > Since we're still calculating NetFee per byte not per KB, how can we calculate that accurately if the tx is just over 1KB after signature is added.
> 
> With zero padding for the big integer amount. The size will be the same for 1 and for 10000000. You will need to compute only twice the transaction, one for get the fee with `0000000000000001`, substract the fee from the amount and sign.
> 
> ![image](https://user-images.githubusercontent.com/3167973/104718392-13a93a80-572b-11eb-9e38-aee467a5eb38.png)

Yeah, size will be the same for 1 and 10000000. But we could have multi addresses in wallet especially the exchange. They often have few gas in many wallet. If one signature is added, the size is bigger then netfee will be increased, if the second address has not enough gas then CLI has to ask the third address for more fee and more recalculate. So the issue is we don't know how many times we have to calculate or CLI will return fault after tried twice.

**Comment by shargon** [comment] 2021-01-15 12:08
We can try it 10 times?

**Closed** 2023-12-05 13:48 UTC
Labels: node
