### ISSUE TITLE
node: Neo3 neo-gui: failed to vote.

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-node#515] opened 2019-12-11 09:43 UTC
I tried to vote, but execution result was false.
![image](https://user-images.githubusercontent.com/43694095/70609351-94e6f180-1c3c-11ea-82d8-090bddbc4be0.png)

Here return false when checkwitness.
![image](https://user-images.githubusercontent.com/43694095/70608902-e5aa1a80-1c3b-11ea-9aed-3b9c308dd8b7.png)

Because cosigner is null.
![image](https://user-images.githubusercontent.com/43694095/70609813-6c132c00-1c3d-11ea-82cf-7abcab96792d.png)

**Comment by shargon** [comment] 2019-12-11 09:57
We will improve neo-gui or create a new one?

**Comment by wanglongfei88** [comment] 2019-12-11 10:10
> We will improve neo-gui or create a new one?

@shargon ,we are creating a new one.

**Comment by shargon** [comment] 2019-12-11 12:06
@wanglongfei88 Then we should close this and mark neo-gui as obsolete

**Comment by wanglongfei88** [comment] 2019-12-16 09:17
> @wanglongfei88 Then we should close this and mark neo-gui as obsolete

Let's keep this GUI before we finished the new one which will take some times since it is going to be a complete different tech stack.

**Comment by shargon** [comment] 2019-12-16 09:56
Then... we should select the cosigner that you want to use it, because now, cosigners are empty

**Comment by nicolegys** [comment] 2019-12-16 14:24
> Then... we should select the cosigner that you want to use it, because now, cosigners are empty

So now we need to provide a place to select the cosigner in this gui?

**Comment by shargon** [comment] 2019-12-16 14:30
Yes, I think that the problem is that we need to select the cosigners, but maybe i am wrong

**Comment by wanglongfei88** [comment] 2019-12-17 07:47
> Yes, I think that the problem is that we need to select the cosigners, but maybe i am wrong

This is a transaction sent by one sender which is signer. I do not understand why we need to select the consigner because there is no one cosign this tx with me.

BTW, I have checked the code. When validating a tx, witnesses is matching sender and consigners both. But when checking witness, witnesses is only matching consigners, exclude sender. The consequence is that a tx will pass tx validation but failed on execution. 

Is it something you guys design for some purpose or a mistake ?

**Comment by shargon** [comment] 2019-12-17 08:43
Could you provide me the raw transaction in order to test it?

**Comment by nicolegys** [comment] 2019-12-17 10:54
my vote tx
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "hash": "0x5e7c7b581ce61bd210edf6f3d490b7a07c92a43e957ff3f16d099d5a8e5a91b7",
        "size": 246,
        "version": 0,
        "nonce": 1371726050,
        "sender": "NQhcLXMUShK1EaK7DPd7Z4XMyucWZy2mpP",
        "sys_fee": "600000000",
        "net_fee": "1246270",
        "valid_until_block": 2104342,
        "attributes": [],
        "cosigners": [],
        "script": "IQLxQ1YtbMH6uWDOJplOsDua4fb8+5YbR9AGGTSrLbSSW1HBFDSCO9DWzZp2WQ72qwqGmOB1HSt1UsEEdm90ZRQVyqBCFDEGcNXlo5jhR+Db7ZjPQ2hifVtS",
        "witnesses": [
            {
                "invocation": "QKaQ09+GhPpcYKS5as4bAY8CNEW8ZPEImfxhaQuku+JCkYfc/HhIricK1g+KxggXTLgzBcD9np17FhsQeihbtrc=",
                "verification": "IQJwfeABt+wcPsTBJbDzpd3+v4yx29FjG+6HeACu8N3BrlBoCpBq1A=="
            }
        ],
        "blockhash": "0xac919a07bab819f9b72297e4cbcf9f0e6180d92e4022ea0272c26dd63bb7f202",
        "confirmations": 2,
        "blocktime": 1576579690919,
        "vmState": "HALT"
    }
}
```

**Closed** 2023-12-05 13:26 UTC
Labels: node
