### ISSUE TITLE
node: Deploy smart-contract error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by im-kulikov** [neo-project/neo-node#392] opened 2019-06-18 12:25 UTC
Steps to reproduce:

- private net ([neo-local](https://github.com/CityOfZion/neo-local))
- NeoCLI 2.10.2.0

```
NEO-CLI Version: 2.10.2.0

neo> open wallet /tmp/wallet1.json
password: ***
neo> deploy /tmp/sc.avm 0710 02 true false true 01.avm 01 NSPCC no-reply@nspcc.ru Test
Script hash: 0x64743d938ee52fa63eb97b101a5e203679213e3b
VM State: HALT
Gas Consumed: 500
Evaluation Stack: [{"type":"InteropInterface"}]

error: Object reference not set to an instance of an object.
```

Simple smart contract take from [here](https://github.com/nspcc-dev/neo-privatenet/blob/master/_test_smart_contract.py)

```
Exception has occurred: CLR/System.NullReferenceException
Exception thrown: 'System.NullReferenceException' in Neo.dll: 'Object reference not set to an instance of an object.'
   at Neo.SmartContract.ContractParametersContext.get_ScriptHashes()
   at Neo.Wallets.Wallet.Sign(ContractParametersContext context)
   at Neo.Shell.MainService.SignAndSendTx(InvocationTransaction tx) in /tmp/neo-cli/neo-cli/Shell/MainService.cs:line 321
```

**Comment by igormcoelho** [comment] 2019-06-18 13:18
Can you put the avm here?

**Comment by im-kulikov** [comment] 2019-06-18 13:20
@igormcoelho yeah [sc.avm.zip](https://github.com/neo-project/neo-cli/files/3301645/sc.avm.zip)

**Comment by im-kulikov** [comment] 2019-06-18 13:24
@igormcoelho it seems like `context` is `null`

```
            ContractParametersContext context;
            try
            {
                context = new ContractParametersContext(tx);
            }
            catch (InvalidOperationException ex)
            {
                Console.WriteLine($"Error creating contract params: {ex}");
                throw;
            }
            Program.Wallet.Sign(context); // << here context is null
```

**Comment by igormcoelho** [comment] 2019-06-18 13:34
Ok, first thing is, it compiles and deploys/runs fine on neocompiler.io. Other thing is that your python code generated a different scripthash than ours.... this is normal also, although not common in python.
Anyway, avm is not parsed, so it should be something else.

I don't see how this could fail:
https://github.com/neo-project/neo/blob/master-2.x/neo/SmartContract/ContractParametersContext.cs#L89-L93

One possibility I think is that `tx` itself is null.... let's see...

**Comment by im-kulikov** [comment] 2019-06-18 13:39
https://github.com/neo-project/neo-cli/blob/55df26b1c41a2550b1f84cac44337a9dec885ed5/neo-cli/Shell/MainService.cs#L182-L184

```
        public InvocationTransaction DecorateInvocationTransaction(InvocationTransaction tx)
        {
            Fixed8 fee = Fixed8.FromDecimal(0.001m);

            if (tx.Size > 1024)
            {
                fee += Fixed8.FromDecimal(tx.Size * 0.00001m);
            }

            return Program.Wallet.MakeTransaction(new InvocationTransaction
            {
                Version = tx.Version,
                Script = tx.Script,
                Gas = tx.Gas,
                Attributes = tx.Attributes,
                Inputs = tx.Inputs,
                Outputs = tx.Outputs
            }, fee: fee);
        }
```

returns `Null`..

**Comment by igormcoelho** [comment] 2019-06-18 13:43
On the same direction here ahahah

**Comment by im-kulikov** [comment] 2019-06-18 13:50
> "sys_fee":"490","net_fee":"-490"

@igormcoelho  how is that possible?

**Comment by igormcoelho** [comment] 2019-06-18 13:51
Script seems good:
```
#324 bytes
04 0: PUSHBYTES4 54657374 # Test
11 5: PUSHBYTES17 6e6f2d7265706c79406e737063632e7275 # no-reply@nspcc.ru
05 23: PUSHBYTES5 4e53504343 # NSPCC
02 29: PUSHBYTES2 3031 # 01
06 32: PUSHBYTES6 30312e61766d # 01.avm
55 39: PUSH5  # The number 5 is pushed onto the stack.
52 40: PUSH2  # The number 2 is pushed onto the stack.
02 41: PUSHBYTES2 0710 # 
4d 44: PUSHDATA2 0115c56b6a00527ac46a51527ac468164e656f2e53746f726167652e476574436f6e74657874616a52527ac46a00c30087642d00144f7065726174696f6e2072657175697265647e21680f4e656f2e52756e74696d652e4c6f67006c7566616a00c303707574876438006a51c300c36a53527ac46a51c351c36a54527ac46a52c36a53c36a54c35272680f4e656f2e53746f726167652e50757461516c7566616a00c30664656c65746587642d006a51c300c36a53527ac46a52c36a53c37c68124e656f2e53746f726167652e44656c65746561516c7566616a00c303676574876429006a51c300c36a53527ac46a52c36a53c37c680f4e656f2e53746f726167652e476574616c756661006c7566 #271 bytes: # 271 bytes pushed onto the stack
68 318: SYSCALL 04f66ca56e # (Contract.Create interop hash)
```

**Comment by im-kulikov** [comment] 2019-06-18 13:53
It seems like problem can be reproduced with `NeoCLI` v2.10.0 - v2.10.2

**Comment by igormcoelho** [comment] 2019-06-18 13:53
Yep, it's strange... this tx is before decorate?

**Comment by im-kulikov** [comment] 2019-06-18 14:04
```json
{
    "txid": "0x4866234227663e87d8f45c501b14042c44060cf6604328344745069f657844a2",
    "size": 341,
    "type": "InvocationTransaction",
    "version": 1,
    "attributes": [],
    "vin": [],
    "vout": [],
    "sys_fee": "490",
    "net_fee": "-490",
    "scripts": [],
    "script": "0454657374116e6f2d7265706c79406e737063632e7275054e535043430230310630312e61766d55520207104d0f010115c56b6a00527ac46a51527ac468164e656f2e53746f726167652e476574436f6e74657874616a52527ac46a00c30087642d00144f7065726174696f6e2072657175697265647e21680f4e656f2e52756e74696d652e4c6f67006c7566616a00c303707574876438006a51c300c36a53527ac46a51c351c36a54527ac46a52c36a53c36a54c35272680f4e656f2e53746f726167652e50757461516c7566616a00c30664656c65746587642d006a51c300c36a53527ac46a52c36a53c37c68124e656f2e53746f726167652e44656c65746561516c7566616a00c303676574876429006a51c300c36a53527ac46a52c36a53c37c680f4e656f2e53746f726167652e476574616c756661006c75666804f66ca56e",
    "gas": "490"
}
```

@igormcoelho this one? yeah, it's `Console.WriteLine("{0}", tx.ToJson())` before calling `tx = DecorateInvocationTransaction(tx);`

**Comment by igormcoelho** [comment] 2019-06-18 14:07
I can only continue later @im-kulikov , but my opinion now is: wallet doesn't have any utxo gas, so no inputs/outputs are attached, and it puts the correct system fee, but since no funds exist, network fee gets negative... and it tries to decorate it anyway (and MakeTransaction detects the error and transforms tx into null), and it tries to relay it (what finally causes the bug).

**Comment by im-kulikov** [comment] 2019-06-18 14:15
@igormcoelho it's strange.. because I use `wallet1.json` (with some amount of gas/neo) and 6k_blocks

**Comment by superboyiii** [comment] 2019-07-22 12:11
@im-kulikov Hey, kulikov. I've just tried your avm, it works well on my neo-cli. And I also tried an address without asset to deploy your sc, it returned the same exception as yours since neo wasn't able to find unspent coins from your address. So I think it's just a correct exception when your asset is null.
Using wallet with enough asset:
![image](https://user-images.githubusercontent.com/38493437/61630995-beb67080-acbb-11e9-8411-78073ff16a82.png)
Using wallet without any asset:
![image](https://user-images.githubusercontent.com/38493437/61631148-2967ac00-acbc-11e9-9ff0-5a21e873fcec.png)
![image](https://user-images.githubusercontent.com/38493437/61631184-3edcd600-acbc-11e9-951a-036e47448e9d.png)
Would you like to use ```list asset``` and ```show utxo``` to confirm if there's any utxo for using.

**Comment by lock9** [comment] 2019-07-22 19:40
Hello,
I removed the bug flag since it looks the bug is not present in the latest version.
I will keep this open so you can finish your tests @im-kulikov. I ask you to please close this issue once the problem is solved.
Thanks.

**Comment by lock9** [comment] 2019-08-01 17:24
@im-kulikov Hello!
I will close this issue since there were no answers for some time. 
If the problem persists and is present in the latest version, please recreate your issue or contact us in Discord.
Thanks

**Comment by im-kulikov** [comment] 2019-08-01 17:30
I was on vacation, could not answer.

**Comment by im-kulikov** [comment] 2019-08-01 17:34
I am testing on NeoLocal with a wallet that has NeoTokens on it.  Including, I use a network in which there are already 6,000 blocks.

**Comment by im-kulikov** [comment] 2019-08-01 17:39
If you repeat the steps that are described, you will get the same result with Neo 2.10.2

**Comment by im-kulikov** [comment] 2019-08-01 17:42
On the other hand, when using NeoPython, I do not get a similar problem.

**Comment by lock9** [comment] 2019-08-01 18:15
Sorry @im-kulikov. Issue reopened!

**Comment by im-kulikov** [comment] 2019-08-01 18:17
Steps to reproduce:
- NeoLocal private network 
- open wallet that presents in container 
- you can find sc.avm above in messages

**Comment by im-kulikov** [comment] 2019-08-01 18:20
stacktrace can also be found in the messages above

**Comment by lock9** [comment] 2019-11-17 23:07
Hello @im-kulikov.  What is the exact version(s) you are using? Thanks.

**Comment by im-kulikov** [comment] 2019-11-18 10:39
@lock9 as described in first message

> Steps to reproduce:
> private net (neo-local)
> NeoCLI 2.10.2.0

**Comment by shargon** [comment] 2023-12-05 13:31
Old, if remains, please re-open

**Closed by shargon** 2023-12-05 13:31 UTC
Labels: node
